dev

diff --git a/scripts/ext_monitor_connect b/scripts/ext_monitor_connect
--- a/scripts/ext_monitor_connect
+++ b/scripts/ext_monitor_connect
@@ -2,6 +2,13 @@
 # Run script when external monitor connects to computer
 # in this situation HDMI cord into laptop (builtin display)
 
-# xrandr --output eDP1 --mode 1366x768 --output HDMI1 --mode 1920x1080 --right-of eDP1
-#xrandr --output eDP1 --mode 1366x768 --pos 0x462 --output HDMI1 --primary --mode 1920x1080 --pos 1366x0
-xrandr --output eDP1 --mode 1920x1080 --output HDMI1 --primary --mode 1920x1080 --right-of eDP1
+#log tag
+LT=HDMI
+
+logger -i -t $LT "Setting resolution for eDP1 and HDMI1"
+if xrandr --output eDP1 --mode 2160x1440 --output HDMI1 --primary --mode 1920x1080 --right-of eDP1; then
+    exit 0
+else
+    logger -is -t $LT "ERROR: Unable to set displays with xrandr"
+    exit 1
+fi
diff --git a/scripts/ext_monitor_disconnect b/scripts/ext_monitor_disconnect
--- a/scripts/ext_monitor_disconnect
+++ b/scripts/ext_monitor_disconnect
@@ -2,4 +2,13 @@
 # Run script when external monitor disconnects from device
 # in this situation HDMI cord from laptop
 
-xrandr --output eDP1 --primary --mode 1920x1080 --output HDMI1 --off &
+#log tag
+LT=HDMI
+
+logger -i -t $LT "Setting resolution for eDP1"
+if xrandr --output eDP1 --primary --mode 2160x1440 --output HDMI1 --off; then
+    exit 0
+else
+    logger -i -t $LT "ERROR: Cannot turn off HDMI"
+    exit 1
+fi
